server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: 'taskmanagement'
  username: 'postgres'
  password: 'Convitcon12'

jwt:
 expiresIn: 3600
 secret: 'authenSecret'
 redis_host: cache